accounts/urls.py
from django.conf.urls import url,include
from . import views
from expenseexpress import settings
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	
	url(r'^register/$', views.register,{ 'template_name':'registration/register.html'},name="register"),
	url(r'^dashboard/$', views.dashboard,{ 'template_name':'registration/dashboard.html'},name="dashboard"),
	url(r'^login/$', views.login,{ 'template_name':"registration/login.html"},name="login"),
	url(r'^logout/$', auth_views.logout,{ 'template_name':"registration/logout.html"},name="logout"),
	url(r'^upload-file/$', views.upload_file,name="upload_file"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

expenseexpress/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import kharch

urlpatterns = [
    # Examples:
    url(r'^$', 'kharch.views.index', name='home'),
    url(r'^kharch/', include('kharch.urls', namespace="kharch")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^utils/', include('utils.urls', namespace="utils")),
    url(r'^admin/', include(admin.site.urls)),
]

kharch/urls.py
from django.conf.urls import include, url
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^add-item/$', views.add_item, name='add_item'),
    url(r'^edit-item/$', views.edit_item, name='edit_item'),
    url(r'^edit-spent/$', views.edit_spent, name='edit_spent'),
    url(r'^delete-item/$', views.delete_item, name='delete_item'),
    url(r'^search-item/$', views.search_item, name='search_item'),
    url(r'^show-items/$', views.show_items, name='show_items'),
    url(r'^buy-error/$', views.buy_error, name='buy_error'),
    url(r'^history/$', views.history, name='history'),
    url(r'^mobile/$', views.show_mobile, name='mobile'),
    url(r'^db-cr/$', views.debit_credit, name='db_cr'),
    url(r'^item/(?P<item_name>[-\w]+)/$', views.get_item,name="get_item"),
    url(r'^pay-due/$', views.pay_due, name='pay_due'),


]

utils/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # Examples:
    url(r'^add-country/$', views.add_country, name='add_country'),
    url(r'^country/$', views.get_countries, name='get_countries'),
    url(r'^(?P<country>[-\w]+)/states/$', views.get_states, name='get_states'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/districts/$', views.get_districts, name='get_districts'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/tehsils/$', views.get_tehsils, name='get_tehsils'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/(?P<tehsil>[-\w]+)/gaons/$', views.get_gaons, name='get_gaons'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/(?P<tehsil>[-\w]+)/(?P<gaon>[-\w]+)/$', views.get_villa, name='get_villa'),
 	url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/district-list/$', views.district_list, name="district_list"),   
]

kharch/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.current_user import get_current_user
from django.db.models import signals
from django.dispatch import receiver

class Payment(models.Model):
	PAYMENT_CODE = (
			("RK", "Rokda"),
			("DB", "Online"),
			("CR", "Credit"),
		)
	name = models.CharField(max_length=10,blank=True, unique=True)
	code = models.CharField(max_length=2, choices=PAYMENT_CODE, default="CR")

	def __str__(self):
		return "%s" % self.name

class PaymentMethod(models.Model):
	url = models.URLField(max_length=200,blank=True)
	code = models.CharField(max_length=10,blank=False,unique=True)

	def __str__(self):
		return self.code


class Cash(models.Model):
	MONEY_TYPE = (
			("ELEC","Electronic"),
			("CASH","Cash"),
		)
	loaded_by = models.ForeignKey(User, default=get_current_user)
	capital = models.PositiveIntegerField(default=0)
	date = models.DateField(auto_now=True)
	form = models.CharField(max_length=4, choices=MONEY_TYPE,default="CASH")

	def __str__(self):
		return "%s" % self.capital

class Category(models.Model):
	CATEGORY_CODE = (
			("RT", "Roti"),
			("KP", "Vastra"),
			("MK", "Ghar"),
			("MB", "Mobile"),
			("OT", "Other"),
		)
	name = models.CharField(max_length=10,blank=True, unique=True)
	code = models.CharField(max_length=2, choices=CATEGORY_CODE, default="RT")

	def __str__(self):
		return "%s" % (self.name)


class Item(models.Model):
	added_by = models.ForeignKey(User, default=get_current_user)
	inherited_by = models.ManyToManyField(User,related_name="inherited")
	name = models.CharField(blank=False,max_length=20,unique=True)
	cost = models.DecimalField(max_digits=5,decimal_places=1)
	category = models.ForeignKey(Category)
	date = models.DateField(auto_now=True)

	def __str__(self):
		return "%s" % (self.name)

class Spent(models.Model):
	spent_by = models.ForeignKey(User, default=get_current_user)
	item 	= models.ForeignKey(Item)
	category = models.ForeignKey(Category)
	price 	= models.DecimalField(max_digits=5,decimal_places=1)
	date 	= models.DateField(blank=False)
	paid 	= models.BooleanField(default=True)
	pay_date = models.DateField(blank=True)
	payment	= models.ForeignKey(Payment)
	validity = models.CharField(max_length=5,default="NA")
	needed 	= models.BooleanField(default=True)

	def __str__(self):
		return "%s %s" % (self.item, self.price)

kharch/forms.py
from django import forms
from .models import Cash, Item
from django.utils.translation import ugettext, ugettext_lazy as _

class CapitalForm(forms.Form):
	capital = forms.IntegerField(label='' )
	hidden = forms.CharField(widget = forms.HiddenInput(attrs={'value':'Capital'}), required = False)

	def __init__(self, *args, **kwargs):
		super(CapitalForm, self).__init__(*args, **kwargs)
		self.fields['capital'].widget.attrs.update({'placeholder' : 'Integer Only'})
		self.fields['capital'].widget.attrs.update({'class' : 'form-control'})

	
class ItemForm(forms.ModelForm):
	error_messages = {'item_match': _("Item already exists."),}

	class Meta:
		model = Item
		fields = ['name', 'cost', 'category']

		labels = {
            'name': _(''),
            'cost': _(''),
            'category':_(''),
        }

	def __init__(self, *args, **kwargs):
		super(ItemForm, self).__init__(*args, **kwargs)
		self.fields['name'].widget.attrs.update({'class' : 'form-control'})
		self.fields['cost'].widget.attrs.update({'class' : 'form-control'})
		self.fields['category'].widget.attrs.update({'class' : 'form-control'})
		self.fields['name'].widget.attrs.update({'placeholder' : 'Item'})
		self.fields['cost'].widget.attrs.update({'placeholder' : 'Cost'})


	def clean_name(self):
		name = self.cleaned_data["name"]
		try:
			name = Item.objects.get(name=name)
		except Item.DoesNotExist:
			return name

		raise forms.ValidationError(u'Item "%s" already exists.' % name)


	def save(self, commit=True):
		item = super(ItemForm, self).save(commit=False)
		item.set_name(self.cleaned_name["name"])
		if commit:
			item.save()
		return item

kharch/views.py
from django.shortcuts import render
from .models import Cash, Spent, Category, Payment, Item
from utils.models import Village
from django.http import HttpResponseRedirect, HttpResponse, Http404
from .forms import CapitalForm, ItemForm
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from utils.current_user import get_current_user
from itertools import chain
import datetime


def index(request):
	user_id = get_current_user()

	if request.method == "GET" and user_id is not None:
		form = CapitalForm()

		cash = Cash.objects.filter(loaded_by=user_id)
		cash = sum(cash.values_list('capital',flat=True))

		items = list(chain(Item.objects.filter(added_by=user_id), Item.objects.filter(inherited_by=user_id) ))

		spent = Spent.objects.filter(spent_by=user_id)

		if len(spent):
			roti = spent.filter(category=Category.objects.get(code="RT"))
			roti = int(sum(roti.values_list('price',flat=True)))

			kapda = spent.filter(category=Category.objects.get(code="KP"))
			kapda = int(sum(kapda.values_list('price',flat=True)))

			makan = spent.filter(category=Category.objects.get(code="MK"))
			makan = int(sum(makan.values_list('price',flat=True)))

			other = spent.filter(category=Category.objects.get(code="OT"))
			other = int(sum(other.values_list('price',flat=True)))

			mobile   = spent.filter(category=Category.objects.get(code="MB"))
			mobile   = int(sum(mobile.values_list('price',flat=True)))

			credit = spent.filter(payment=Payment.objects.get(code="CR")).filter(paid=False)
			credit = int(sum(credit.values_list('price',flat=True)))
			
			online = spent.filter(payment=Payment.objects.get(code="DB")).filter(paid=True)
			online  = int(sum(online.values_list('price',flat=True)))
			
			remain = cash - sum([roti,kapda,makan,other,mobile]) + credit + online

		else:
			roti = kapda = makan = other = mobile = 0
			remain = cash

		
		context = {}
		context['cash'] = remain
		context['roti'] = roti
		context['kapda'] = kapda
		context['makan'] = makan
		context['other'] = other
		context['mobile'] = mobile
		context['form'] = form
		context['items'] = items
		context['meta_keywords'] = "Overrided Meta Keywords"
		return render(request, 'kharch/index.html', context)

	if request.method == "POST" and user_id is not None:

		if request.POST['hidden'] == 'Capital':
			form = CapitalForm(request.POST)
			if form.is_valid():
				capital = int(request.POST['capital'])
				if capital > 0 :
					Cash.objects.create(capital=capital)

		elif request.POST['hidden'] == 'Item':
			total = 0.0
			brought = request.POST.getlist('items[]')
			
			for item in brought:
				payment_mode = "%s_sel" % request.POST[item]
				if payment_mode == "RK":
					total += float(request.POST[item])

			cash = Cash.objects.filter(loaded_by=user_id)
			cash = sum(cash.values_list('capital',flat=True))

			spent = Spent.objects.filter(spent_by=user_id)
			
			if len(spent):
				roti = spent.filter(category=Category.objects.get(code="RT"))
				roti = int(sum(roti.values_list('price',flat=True)))

				kapda = spent.filter(category=Category.objects.get(code="KP"))
				kapda = int(sum(kapda.values_list('price',flat=True)))

				makan = spent.filter(category=Category.objects.get(code="MK"))
				makan = int(sum(makan.values_list('price',flat=True)))

				other = spent.filter(category=Category.objects.get(code="OT"))
				other = int(sum(other.values_list('price',flat=True)))

				mobile   = spent.filter(category=Category.objects.get(code="MB"))
				mobile   = int(sum(mobile.values_list('price',flat=True)))

				credit = spent.filter(payment=Payment.objects.get(code="CR")).filter(paid=False)
				credit = int(sum(credit.values_list('price',flat=True)))
				
				online = spent.filter(payment=Payment.objects.get(code="DB")).filter(paid=True)
				online  = int(sum(online.values_list('price',flat=True)))
				
				remain = cash - sum([roti,kapda,makan,other,mobile]) + credit + online
				
			else:
				roti = kapda = makan = other = mobile = 0
				remain = cash

			if total > remain:
				url = urlresolvers.reverse('kharch:buy_error')
				return HttpResponseRedirect(url)

			for item in brought:
				payment = request.POST[item+"_sel"]
				obj = Item.objects.get(name=item)
				category = obj.category
				added_by = obj.added_by
				append = request.POST.getlist('append[]')
				date = request.POST["buy_date_"+item]
				date = datetime.datetime.strptime(date, '%d/%m/%Y').strftime('%Y-%m-%d')
				if item in append :
					obj.inherited_by.add(user_id)
					obj.save()
				paid = False if payment == "CR" else True
				validity = 28 if obj.category.code == "MB" else 0
				Spent.objects.create(item=obj, paid=paid, validity=validity, category=Category.objects.get(id=obj.category_id), payment=Payment.objects.get(code=payment), price=request.POST[item], date=date, pay_date=date)

		return HttpResponseRedirect(".")

	else:
		url = urlresolvers.reverse('accounts:login')
		return HttpResponseRedirect(url)

@login_required
def buy_error(request):
	if request.method == "GET":
		return render(request, 'kharch/error.html', {})


@login_required
def add_item(request):
	form = ItemForm()
	if request.method == "GET":
		context = {}
		context['form'] = form
		return render(request, 'kharch/add_item.html', context)

	elif request.method == "POST":
		form = ItemForm(request.POST)
		if form.is_valid():
			name = request.POST['name']
			cost = request.POST['cost']
			category = request.POST['category']

			Item.objects.create(name=name, cost=cost, category=Category.objects.get(id=category))
			
			url = urlresolvers.reverse('kharch:add_item')
			return HttpResponseRedirect(url)
		else:
			context = {}
			form = ItemForm()
			context['form'] = form
			context['error'] = "Item already exists."
			return render(request, 'kharch/add_item.html', context)

@login_required
def edit_item(request):
	user_id = get_current_user()
	if request.method == "GET":
		form = ItemForm()
		items = Item.objects.filter(added_by=user_id)
		context = {}
		context['form'] = form
		context['items'] = items
		return render(request, 'kharch/edit_item.html', context)

	elif request.method == "POST":
		edited = request.POST.getlist('items[]')
		for item in edited:
			obj = Item.objects.get(name=item)
			name = request.POST[item] 
			cost = request.POST[item+"_cost"]
			category = request.POST[item+"_sel"]
			try :
				exists = Item.objects.get(name=name)
				exists = True
			except:
				exists = False
			if not exists:
				obj.name = name
				obj.cost = cost
				obj.category = Category.objects.get(code=category)
				obj.save()

		url = urlresolvers.reverse('kharch:edit_item')
		return HttpResponseRedirect(url)


@login_required
def edit_spent(request):
	user_id = get_current_user()
	if request.method == "GET":
		context = {}
		return render(request,'kharch/mobile.html',context)

	else:
		if "dashboard" in request.POST:
			spent_id = int(request.POST['dashboard'])
			spent = Spent.objects.get(pk=spent_id)
			spent_date = request.POST['spent_date_%s' %request.POST['dashboard']].split("-")
			year,month,day = [int(part) for part in spent_date]
			spent.date = datetime.date(year,month,day)
			spent.validity = int(request.POST['validity']) if request.POST['validity'] != "NA" else "NA"
			spent.cost = float(request.POST['cost'])
			spent.payment = Payment.objects.get(code=request.POST['%d_sel' % spent_id])
			spent.save()
			url = urlresolvers.reverse('accounts:dashboard')
			return HttpResponseRedirect(url)
		else:
			spent_id = int(request.POST['hidden'])
			spent = Spent.objects.get(pk=spent_id)
			spent_date = request.POST['spent_date_%s' %request.POST['hidden']].split("-")
			year,month,day = [int(part) for part in spent_date]
			spent.date = datetime.date(year,month,day)
			spent.validity = int(request.POST['validity']) if request.POST['validity'] != "NA" else "NA"
			spent.cost = float(request.POST['cost'])
			spent.payment = Payment.objects.get(code=request.POST['%d_sel' % spent_id])
			spent.save()
			url = urlresolvers.reverse('kharch:mobile')
			return HttpResponseRedirect(url)

@login_required
def delete_item(request):
	user_id = get_current_user()
	if request.method == "GET":
		form = ItemForm()
		items = Item.objects.filter(added_by=user_id)
		context = {}
		context['form'] = form
		context['items'] = items
		return render(request, 'kharch/delete_item.html', context)

	elif request.method == "POST":
		edited = request.POST.getlist('items[]')
		flag = False
		for item in edited:
			spent = Spent.objects.filter(item=Item.objects.get(name=item))
			if len(spent) < 1:
				obj = Item.objects.get(name=item)
				obj.delete()
			else:
				flag = True

		if flag:
			form = ItemForm()
			items = Item.objects.filter(added_by=user_id)
			context = {}
			context['form'] = form
			context['error'] = "Already purchased items cannot be deleted. Contact Admin"
			context['items'] = items
			return render(request, 'kharch/delete_item.html', context)
		else:
			url = urlresolvers.reverse('kharch:delete_item')
			return HttpResponseRedirect(url)
	
@login_required
def history(request):
	user_id = get_current_user()
	context = {}

	items = list(chain(Item.objects.filter(added_by=user_id), Item.objects.filter(inherited_by=user_id)))
	
	spent = Spent.objects.filter(spent_by=user_id)

	roti = spent.filter(category=Category.objects.get(code="RT"))
	roti = int(sum(roti.values_list('price',flat=True)))

	kapda = spent.filter(category=Category.objects.get(code="KP"))
	kapda = int(sum(kapda.values_list('price',flat=True)))

	makan = spent.filter(category=Category.objects.get(code="MK"))
	makan = int(sum(makan.values_list('price',flat=True)))

	other = spent.filter(category=Category.objects.get(code="OT"))
	other = int(sum(other.values_list('price',flat=True)))

	mobile   = spent.filter(category=Category.objects.get(code="MB"))
	mobile = int(sum(mobile.values_list('price',flat=True)))

	series = []
	for item in items:

kharch/templates/kharch/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="{{ meta_description }}">
		<meta name="keywords" content="{{ meta_keywords }}">
    
    <link rel="stylesheet" href="{% static 'kharch/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'kharch/css/navbar-fixed-top.css' %}"/>
    <link rel="stylesheet" href="{% static 'kharch/css/signin.css' %}"/>
    <link rel="stylesheet" href="{% static 'kharch/css/theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'kharch/css/daterangepicker.css' %}"/>

    <script type="text/javascript" src="{% static 'kharch/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'kharch/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'kharch/js/kharch.js' %}"></script>
    <script type="text/javascript" src="{% static 'kharch/js/moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'kharch/js/daterangepicker.js' %}"></script>

    {% block title %} {% endblock %}
    {% block css %} {% endblock %}
    {% block js %} {% endblock %}
		
	</head>

<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'kharch:home' %}">ExpenseExpress</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li> 
            <form class="navbar-form navbar-left" role="search" method="post" action="{% url 'kharch:show_items' %}">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" id="sug" oninput="show_suggestion(this)" name="suggest" placeholder="Search an item">

              </div>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
              <div class="form-group">
                <input type="text" class="form-control" name="suggested" id="suggested" style="display:none">

              </div>
            </form>
          </li>
        </ul>
      	<ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'kharch:db_cr' %}">DB and CR</a></li>
          <li><a href="{% url 'utils:get_countries' %}">Villages</a></li>
          {% if request.user.username %}
          <li><a href="{% url 'kharch:mobile' %}">MobileExpress</a></li>
      		<li><a href="{% url 'accounts:dashboard' %}">{{ request.user.username|capfirst }}</a></li>
          <li><a href="{% url 'kharch:history' %}">History</a></li>
          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          {% endif %}
      	</ul>
      </div>
    </div>
  </nav>
  
  {% block site_wrapper %} {% endblock %}
  
</body>

</html>

kharch/templates/kharch/db_cr.html
{% extends "kharch/base.html" %}
{% load staticfiles %}
{% load customtags %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}

{% endblock %}

{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
		          <table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>Name</th>
		                <th>Category</th>
		                <th>Price</th>
		                <th>Date</th>
		                <th>Mode(CR/DB)</th>
		                <th>Paid</th>
		                <th>Pay Date</th>
		                
		              </tr>
		            </thead>
		            <tbody>
		            {%for onln in online%}
		            	<tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'kharch:get_item'  item_name=onln.item %}"> {{ onln.item}} </a> </td>
			            	<td>{{ onln.category }}</td>
			            	<td>{{ onln.price }}</td>
			            	<td>{{ onln.date }}</td>
			            	<td> {{ onln.payment.code }}</td>
			            	<td> {{ onln.paid }}</td>
			            	<td>{{ onln.pay_date }}</td>
			            </tr>
		            {% endfor %}
		            <br><br>
		            {%for cr in credit %}
		            	<tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'kharch:get_item'  item_name=cr.item %}"> {{ cr.item}} </a> </td>
			            	<td>{{ cr.category }}</td>
			            	<td>{{ cr.price }}</td>
			            	<td>{{ cr.date }}</td>
			            	<td> {{ cr.payment.code }}</td>
			            	<td> {{ cr.paid }}</td>
			            	<td>{{ cr.pay_date }}</td>
			            </tr>
		            {% endfor %}
		            </tbody>
		          </table>
		        </div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		// $(function() {
		//     $('input[name^="spent_date"]').daterangepicker({
		//         singleDatePicker: true,
		//         showDropdowns: true,
		        
		//     });
		// });
	</script>

{% endblock %}

kharch/templates/kharch/mobile.html
{% extends "kharch/base.html" %}
{% load staticfiles %}
{% load customtags %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}

{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="table-responsive">
		          <table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>Name</th>
		                <th>Cost</th>
		                <th>Date</th>
		                <th>Validity</th>
		                <th>Status</th>
		                
		              </tr>
		            </thead>
		            <tbody>
		            {% for spent in spents %}
		            <form method="post" action="{% url 'kharch:edit_spent' %}">
		            	{% csrf_token %}
		            	<div id="{{spent.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="{{spent.item}}">
						    <div class="modal-dialog">
						      <div class="modal-content">

						        <div class="modal-header">
						          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
						          <h4 class="modal-title" id="{{spent.item}}">{{spent.item}}</h4>
						        </div>
						        <div class="modal-body">
						        	<input type="text" name="cost" value="{{spent.price}}" class="form-control"><br>
						        	<input type="text" name="spent_date_{{spent.id}}" value="{{spent.date|date:'Y-m-d'}}" class="form-control" placeholder="YYYY-mm-dd" /><br>
						        	<input type="text" name="validity" placeholder="in days" value="{{spent.validity}}" class="form-control" /><br>
						        	<select name="{{spent.id}}_sel" class="form-control">

                        {% for pay in payment %}
                          
                          {% if spent.payment.code == pay.code  %}
                            <option value="{{ pay.code }}" selected>{{ pay.name }}</option>
                          {% else %}
                            <option value="{{ pay.code }}">{{ pay.name }}</option>
                          {% endif %}
                        {% endfor %}
                        </select>

						        	<input type="hidden" name="hidden" value="{{spent.id}}">
						        </div>
						        <div class="modal-footer">
						          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						          <button type="submit" class="btn btn-primary">Save</button>
						        </div>
						      </div>
						    </div>
						  </div>
						  </form>
			            <tr>
			            	<td>{{forloop.counter}}</td>
			                <td><a href="{% url 'kharch:get_item'  item_name=spent.item %}"> {{spent.item}}</a></td>
			                <td>{{spent.price}}</td>
			                <td>{{spent.date}}</td>
			                <td>{{spent.validity}}</td>
			                
			                <td>

			                	{% if status|status:forloop.counter0 == "Green"%}
			                		<button class="btn btn-success btn-xs" type="submit" alt="Green" id="green">{{ valid|valid:forloop.counter0 }}</button>
			                	{% endif %}

			                	{% if status|status:forloop.counter0 == "Yellow"%}
			                		<button class="btn btn-warning btn-xs" type="submit" alt="Yellow" id="yellow">{{ valid|valid:forloop.counter0 }}</button>
			                	{% endif %}

			                	{% if status|status:forloop.counter0 == "Red"%}
			                		<button class="btn btn-danger btn-xs" type="submit" alt="Red" id="red">{{ valid|valid:forloop.counter0 }}</button>
			                	{% endif %}

			                	<button class="btn btn-info btn-xs" data-toggle="modal" data-target="#{{spent.id}}">Edit</button>


			                </td>
		              </tr>

		            {% endfor %}
		            </tbody>
		          </table>
		        </div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		// $(function() {
		//     $('input[name^="spent_date"]').daterangepicker({
		//         singleDatePicker: true,
		//         showDropdowns: true,
		        
		//     });
		// });
	</script>

{% endblock %}

kharch/templates/kharch/pay_due.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
	
{% endblock %}



{% block site_wrapper %}
<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				
				<p class="btn-success"> Your dues have been paid. </p>

			</div>
		</div>
</div>


{% endblock %}