expenseexpress/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import kharch

urlpatterns = [
    # Examples:
    url(r'^$', 'kharch.views.index', name='home'),
    url(r'^kharch/', include('kharch.urls', namespace="kharch")),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^utils/', include('utils.urls', namespace="utils")),
    url(r'^admin/', include(admin.site.urls)),
]

utils/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    # Examples:
    url(r'^add-country/$', views.add_country, name='add_country'),
    url(r'^country/$', views.get_countries, name='get_countries'),
    url(r'^(?P<country>[-\w]+)/states/$', views.get_states, name='get_states'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/districts/$', views.get_districts, name='get_districts'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/tehsils/$', views.get_tehsils, name='get_tehsils'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/(?P<tehsil>[-\w]+)/gaons/$', views.get_gaons, name='get_gaons'),
    url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/(?P<district>[-\w]+)/(?P<tehsil>[-\w]+)/(?P<gaon>[-\w]+)/$', views.get_villa, name='get_villa'),
 	url(r'^(?P<country>[-\w]+)/(?P<state>[-\w]+)/district-list/$', views.district_list, name="district_list"),   
]

utils/models.py
from django.db import models

class Country(models.Model):
	name = models.CharField(blank=False,max_length=50, unique=True)
	abrcode = models.CharField(blank=False,max_length=10, unique=True)
	url = models.URLField(max_length=100, unique=True, blank=True)
	code = models.CharField(blank=False, max_length=10, unique=True)
	scount = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "%s" % self.name

class State(models.Model):
	country = models.ForeignKey(Country)
	state = models.CharField(blank=False, max_length=70)
	abrcode = models.CharField(blank=True, max_length=10)
	url = models.URLField(max_length=100, blank=True)
	vcount = models.PositiveIntegerField(default=0)
	code = models.CharField(blank=True, max_length=10)

	def __str__(self):
		return "%s" % self.state

class District(models.Model):
	state = models.ForeignKey(State)
	district = models.CharField(blank=False, max_length=100)
	abrcode = models.CharField(blank=True, max_length=10)
	url = models.URLField(max_length=100, blank=True)
	vcount = models.PositiveIntegerField(default=0)
	code = models.CharField(blank=True, max_length=10)
	hq = models.CharField(blank=True, max_length=100)
	population = models.PositiveIntegerField(default=0)
	area = models.PositiveIntegerField(default=0)
	density = models.PositiveIntegerField(default=0)

	def __str__(self):
		return "%s" % self.district

class Tehsil(models.Model):
	district = models.ForeignKey(District)
	tehsil =  models.CharField(blank=False, max_length=100)
	abrcode = models.CharField(blank=True, max_length=10)
	url = models.URLField(max_length=100, blank=True)
	vcount = models.PositiveIntegerField(default=0)
	code = models.CharField(blank=True, max_length=10)

	def __str__(self):
		return "%s" % self.tehsil

class Village(models.Model):
	tehsil = models.ForeignKey(Tehsil)
	village =  models.CharField(blank=False, max_length=100)
	abrcode = models.CharField(blank=True, max_length=10)
	url = models.URLField(max_length=100, blank=True)
	pincode = models.PositiveIntegerField(blank=True)
	
	def __str__(self):
		return "%s" % self.village

utils/forms.py
from django import forms
from .models import Country
from django.utils.translation import ugettext, ugettext_lazy as _


class CountryForm(forms.ModelForm):
	error_messages = {'country_match': _("Country already exists."),}

	class Meta:
		model = Country
		fields = ('name', 'abrcode', 'url', 'code')

		labels = {
            'name': _(''),
            'abrcode': _(''),
            'url':_(''),
            'code':_(''),
        }

	def __init__(self, *args, **kwargs):
		super(CountryForm, self).__init__(*args, **kwargs)
		self.fields['name'].widget.attrs.update({'class' : 'form-control'})
		self.fields['abrcode'].widget.attrs.update({'class' : 'form-control'})
		self.fields['url'].widget.attrs.update({'class' : 'form-control'})
		self.fields['code'].widget.attrs.update({'class' : 'form-control'})

		self.fields['name'].widget.attrs.update({'placeholder' : 'Country'})
		self.fields['abrcode'].widget.attrs.update({'placeholder' : 'Abrivation'})
		self.fields['url'].widget.attrs.update({'placeholder' : 'Url'})
		self.fields['code'].widget.attrs.update({'placeholder' : 'Code'})



	def clean_name(self):
		name = self.cleaned_data["name"]
		try:
			name = Country.objects.get(name=name)
		except Country.DoesNotExist:
			return name

		raise forms.ValidationError(u'Country "%s" already exists.' % name)


	def save(self, commit=True):
		country = super(CountryForm, self).save(commit=False)
		country.set_name(self.cleaned_name["name"])
		if commit:
			country.save()
		return country

utils/views.py
from django.shortcuts import render
from .models import Country, State, District, Tehsil, Village
from django.http import HttpResponseRedirect, HttpResponse, Http404
from .forms import CountryForm
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from utils.current_user import get_current_user
from itertools import chain
import datetime
import bharat as bh
import data
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from utils.serializers import DistrictSerializer

class JSONResponse(HttpResponse):
	def __init__(self, data, **kwargs):
		content = JSONRenderer().render(data)
		kwargs['content_type'] = 'application/json'
		super(JSONResponse, self).__init__(content, **kwargs)

@csrf_exempt
def district_list(request,country, state):
	if request.method == "GET":
		country_obj = Country.objects.get(abrcode=country)
		state_obj = [st for st in State.objects.filter(country=country_obj) if st.abrcode == state][0]
		districts = District.objects.all().filter(state=state_obj)
		serializer = DistrictSerializer(districts, many=True)
		return JSONResponse(serializer.data)

	elif request.method == 'POST':
		data = JSONParser().parse(request)
		serializer = DistrictSerializer(data=data)
		if serializer.is_valid():
			serializer.save()
			return JSONResponse(serializer.data, status=201)
		return JSONResponse(serializer.errors, status=400)


def add_country(request):
	if request.method == "GET":
		context = {}
		context['form'] = CountryForm()
		return render(request, 'utils/add_country.html', context)

	else:
		country = request.POST['name']
		abrcode = request.POST['abrcode']
		url = request.POST['url']
		code = request.POST['code']
		Country.objects.update_or_create(name=country, abrcode=abrcode, url=url, code=code)
		url = urlresolvers.reverse('utils:add_country')
		return HttpResponseRedirect(url)

def get_countries(request):
	if request.method == "GET":
		context = {}
		context['countries'] = Country.objects.all()
		return render(request, 'utils/country.html', context)


def get_states(request, country):
	country = Country.objects.get(abrcode=country)
	if request.method == "GET":
		context = {}
		states = State.objects.all().filter(country=country)
		context['states'] = states
		context['country'] = country
		return render(request, 'utils/states.html', context)

	else:
		country_url = "http://vlist.in/"
		try:
			states = bh.get_states(country_url)
		except:
			states = []

		for state in states:
			name, link, count = state
			abrcode = name[:2].upper()
			st = State.objects.update_or_create(
					country=country,
					state=name,
					url=link,
					vcount=count,
					abrcode=abrcode,
				)

		country.scount = State.objects.filter(country=country).count()
		country.save()

		url = urlresolvers.reverse('utils:get_states', kwargs={'country': country.abrcode})
		return HttpResponseRedirect(url)

def get_districts(request, country, state):
	state = str(state)
	country_obj = Country.objects.get(abrcode=country)
	state_obj = [st for st in State.objects.all().filter(country=country_obj) if st.abrcode == state][0]
	if request.method == "GET":
		context = {}
		districts = [district for district in District.objects.all().filter(state=state_obj)]
		context['districts'] = districts
		context['country'] = country_obj
		context['state'] = state_obj
		return render(request, 'utils/district.html', context)

	else:
		try:
			districts = bh.get_districts(state_obj.url)
		except:
			districts = []

		for district in districts:
			name, link, count = district
			abrcode = name[:3].upper()
			dt = District.objects.update_or_create(
					state=state_obj,
					district=name,
					url=link,
					abrcode=abrcode,
					vcount=count,
				)

		url = urlresolvers.reverse('utils:get_districts', kwargs={'country': country ,'state': state })
		return HttpResponseRedirect(url)



def get_tehsils(request, country, state, district):
	state = str(state)
	district = str(district)
	country_obj = Country.objects.get(abrcode=country)
	state_obj = [st for st in State.objects.all().filter(country=country_obj) if st.abrcode == state][0]
	dist_obj = [dt for dt in District.objects.all().filter(state=state_obj) if dt.abrcode == district][0]
	if request.method == "GET":
		context = {}
		tehsils = [tehsil for tehsil in Tehsil.objects.all().filter(district=dist_obj)]
		context['tehsils'] = tehsils
		context['country'] = country_obj
		context['state'] = state_obj
		context['district'] = dist_obj
		return render(request, 'utils/tehsils.html', context)

	else:
		try:
			
			tehsils = bh.get_tehsils(dist_obj.url)
		except:
			tehsils = []

		for tehsil in tehsils:
			name, link, count = tehsil
			abrcode = name[:3].upper()
			th = Tehsil.objects.update_or_create(
					district=dist_obj,
					tehsil=name,
					url=link,
					vcount=count,
					abrcode=abrcode,
				)

		url = urlresolvers.reverse('utils:get_tehsils', kwargs={'country': country, 'state': state, 'district': district})
		return HttpResponseRedirect(url)

def get_gaons(request, country, state, district, tehsil):
	country = str(country)
	state = str(state)
	district = str(district)
	tehsil = str(tehsil)
	country_obj = Country.objects.get(abrcode=country)
	state_obj = [st for st in State.objects.all().filter(country=country_obj) if st.abrcode == state][0]
	dist_obj = [dt for dt in District.objects.all().filter(state=state_obj) if dt.abrcode == district][0]
	tehsil_obj = [th for th in Tehsil.objects.all().filter(district=dist_obj) if th.abrcode == tehsil][0]

	if request.method == "GET":
		gaons = [gaon for gaon in Village.objects.all().filter(tehsil=tehsil_obj)]
		context = {}
		context['district'] = dist_obj
		context['country'] = country_obj
		context['state'] = state_obj
		context['tehsil'] = tehsil_obj
		context['gaons'] = gaons
		return render(request, 'utils/gaons.html', context)

	else:
		try:
			gaons = bh.get_gaons(tehsil_obj.url)
		except:
			gaons = []

		for gaon in gaons:
			name, link, pincode = gaon
			abrcode = name[:3].upper()
			vg = Village.objects.update_or_create(
					tehsil=tehsil_obj,
					abrcode=abrcode,
					village=name,
					url=link,
					pincode=pincode,
				)

		url = urlresolvers.reverse('utils:get_gaons', kwargs={'country': country, 'state': state, 'district': district, 'tehsil':tehsil })
		return HttpResponseRedirect(url)


def get_villa(request, country, state, district, tehsil, gaon):
	country_obj = Country.objects.get(abrcode=country)
	state_obj = [st for st in State.objects.all().filter(country=country_obj) if st.abrcode == state][0]
	dist_obj = [dt for dt in District.objects.all().filter(state=state_obj) if dt.abrcode == district][0]
	tehsil_obj = [th for th in Tehsil.objects.all().filter(district=dist_obj) if th.abrcode == tehsil][0]
	villa = [villa for villa in Village.objects.all().filter(tehsil=tehsil_obj) if villa.abrcode == gaon][0]
	if request.method == "GET":
		context = {}
		context['villa'] = villa
		context['country'] = country_obj
		context['state'] = state_obj
		context['district'] = dist_obj
		context['tehsil'] = tehsil_obj
		return render(request, 'utils/villa.html', context)

utils/templates/utils/add_country.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
<script type="text/javascript">
	function checkForm(){
		item = document.getElementById("id_name").value;
		if (item == ""){
			$("#alert_message h4").text("Add country name.");
			$("#alert_message").css('display','block');
			return false;
		}

		cost = document.getElementById("id_abrcode").value;
		if (cost == ""){
			$("#alert_message h4").text("Add abreviation code for country.");
			$("#alert_message").css('display','block');
			return false;
		}

		return true;
		
	}
</script>

{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-3"></div>
			<div class="col-md-4">
				<div id="alert_message" class="alert alert-danger alert-dismissible fade in" style="display:none">

					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">×</span></button> 
					<h4></h4> 
				 </div>

				<form action="{% url 'utils:add_country' %}" method="post">
					{% csrf_token %}
					{{ form.as_p}}
					
					<button class="btn  btn-success btn-block " type="submit" alt="Add Country" onclick="return checkForm(this);">Add Country</button>
					<a class="btn btn-info btn-block" href="{% url 'utils:get_countries'%}" role="button">Country</a>
				</form>
			</div>
			<div class="col-md-5"></div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/country.html
{% extends "kharch/base.html" %}
{% load staticfiles %}
{% load customtags %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}

{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>Country</th>
		                <th>Abrivation</th>
		                <th>States</th>
		                <th>URL</th>
		                <th>Code</th>
		                <th>Total</th>
		              </tr>
		            </thead>
		            <tbody>

		            {% for desh in countries %}
			            <tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'utils:get_states' country=desh.abrcode %}"> {{ desh.name}} </a> </td>
			            	<td>{{ desh.abrcode }}</td>
			            	<td>{{ desh.scount }}</td>
			            	<td> <a href="{{ desh.url }}"> {{ desh.url }} </a> </td>
			            	<td>{{ desh.code }}</td>
			            	<td>{{ desh.abrcode|vcount }}</td>
			            </tr>
			        {% endfor %}
			        </tbody>
			    </table>
			    <div class="col-md-3 col-md-offset-4">
			    <a class="btn btn-success btn-block" href="{% url 'utils:add_country' %}" role="button">Add Country</a>
			    </div>

			</div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/district.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="{% url 'utils:get_states' country=country.abrcode%}">{{country.name}}</a> => 
				<a href="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}">{{state.state}}</a> =>
				<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>District</th>
		                <th>Count</th>
		                <th>Population</th>
		                <th>Area/km2</th>
		                <th>Density/km2</th>
		              </tr>
		            </thead>
		            <tbody>
		            {% for dt in districts %}
			            <tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'utils:get_tehsils' country=dt.state.country.abrcode state=dt.state.abrcode district=dt.abrcode %}">{{ dt.district }} </a> </td>
			            	<td>{{ dt.vcount }}</td>
			            	<td>{{ dt.population }}</td>
			            	<td>{{ dt.area }}</td>
			            	<td>{{ dt.density }}</td>
			            </tr>
			        {% endfor %}
			        </tbody>
			    </table>
			    {% if districts|length == 0 %}

			    <form action="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Download">Download</button>
			    	
			    </form>

			    {% endif %}

			    {% if districts|length > 0 %}
			    <br>
			    <form action="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Update">Update</button>
			    	
			    </form>
			    {% endif %}
			    
			</div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/gaons.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="{% url 'utils:get_states' country=country.abrcode%}">{{country.name}}</a> => 
				<a href="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}">{{state.state}}</a> =>
				<a href="{% url 'utils:get_tehsils' country=country.abrcode state=state.abrcode district=district.abrcode %}">{{district.district}}</a> =>
				<a href="{% url 'utils:get_gaons' country=country.abrcode state=state.abrcode district=district.abrcode tehsil=tehsil.abrcode %}">{{tehsil.tehsil}}</a> =>
				
				<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>Village</th>
		                <th>Pincode</th>
		              </tr>
		            </thead>
		            <tbody>
		            {% for gn in gaons %}
			            <tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'utils:get_villa' country=gn.tehsil.district.state.country.abrcode state=gn.tehsil.district.state.abrcode district=gn.tehsil.district.abrcode tehsil=gn.tehsil.abrcode gaon=gn.abrcode %}">{{ gn.village }} </a> </td>
			            	<td>{{ gn.pincode }}</td>
			            </tr>
			        {% endfor %}
			        </tbody>
			    </table>
			    {% if gaons|length == 0 %}

			    <form action="{% url 'utils:get_gaons' country=country.abrcode state=state.abrcode district=district.abrcode tehsil=tehsil.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Download">Download</button>
			    	
			    </form>

			    {% endif %}
			    
			</div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/states.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
{% endblock %}

{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="{% url 'utils:get_states' country=country.abrcode%}">{{country.name}}</a> => States
				{% if states|length > 0%}
				<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>State</th>
		                <th>Abrivation</th>
		                <th>Count</th>
		                <th>Population</th>
		              </tr>
		            </thead>
		            <tbody>
		            
		            {% for st in states %}
			            <tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td><a href="{% url 'utils:get_districts' country=st.country.abrcode state=st.abrcode %}">{{ st.state }}</a> </td>
			            	<td>{{ st.abrcode }} </td>
			            	<td>{{ st.vcount }}</td>
			            	<td>NA</td>
			            </tr>
			        {% endfor %}
			        </tbody>
			    </table>

			    {% else %}
			    <br>
			    <form action="{% url 'utils:get_states' country=country.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Download">Download</button>
			    	
			    </form>
			    {% endif %}
			    
			    {% if states|length > 0 %}
			    <br>
			    <form action="{% url 'utils:get_states' country=country.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Update">Update</button>
			    	
			    </form>
			    {% endif %}
			    
			</div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/tehsils.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="{% url 'utils:get_states' country=country.abrcode %}">{{country.name}}</a> => 
				<a href="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}">{{state.state}}</a> =>
				<a href="{% url 'utils:get_tehsils' country=country.abrcode state=state.abrcode district=district.abrcode %}">{{district.district}}</a> =>
				<table class="table table-striped">
		            <thead>
		              <tr>
		                <th>#</th>
		                <th>Tehsil</th>
		                <th>Abrivation</th>
		                <th>Count</th>
		                <th>Code</th>
		              </tr>
		            </thead>
		            <tbody>
		            {% for th in tehsils %}
			            <tr>
			            	<td>{{ forloop.counter }}</td>
			            	<td> <a href="{% url 'utils:get_gaons' country=th.district.state.country.abrcode state=th.district.state.abrcode district=th.district.abrcode tehsil=th.abrcode %}">{{ th.tehsil }} </a> </td>
			            	<td>{{ th.abrcode }}</td>
			            	<td>{{ th.vcount }}</td>
			            	<td>{{ th.code }}</td>
			            </tr>
			        {% endfor %}
			        </tbody>
			    </table>
			    {% if tehsils|length == 0 %}

			    <form action="{% url 'utils:get_tehsils' country=country.abrcode state=state.abrcode district=district.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Download">Download</button>
			    	
			    </form>

			    {% endif %}

			    {% if tehsils|length > 0 %}

			    <form action="{% url 'utils:get_tehsils' country=country.abrcode state=state.abrcode district=district.abrcode %}" method="post">
			    	{% csrf_token %}
			    	<button class="btn  btn-success" type="submit" alt="Update">Update</button>
			    	
			    </form>

			    {% endif %}
			    
			</div>
		</div>
	</div>
	
{% endblock %}

utils/templates/utils/villa.html
{% extends "kharch/base.html" %}
{% load staticfiles %}

{% block title %}
	<title > Manage your Expense | ExpenseExpress </title>
{% endblock %}

{% block css %}

{% endblock %}
	
{% block js %}
{% endblock %}



{% block site_wrapper %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="{% url 'utils:get_states' country=country.abrcode%}">{{country.name}}</a> => 
				<a href="{% url 'utils:get_districts' country=country.abrcode state=state.abrcode %}">{{state.state}}</a> =>
				<a href="{% url 'utils:get_tehsils' country=country.abrcode state=state.abrcode district=district.abrcode %}">{{district.district}}</a> =>
				<a href="{% url 'utils:get_gaons' country=country.abrcode state=state.abrcode district=district.abrcode tehsil=tehsil.abrcode %}">{{tehsil.tehsil}}</a> =>
				{{ villa.village }}
								
			</div>
		</div>
	</div>
	
{% endblock %}